#!/bin/zsh
#
#   This file is part of Dash Ninja.
#   https://github.com/elbereth/dashninja-ctl
#
#   Dash Ninja is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Dash Ninja is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with Dash Ninja.  If not, see <http://www.gnu.org/licenses/>.
#

# Disable logging by default
blockdegapperlog=/dev/null
blockparserlog=/dev/null
blocksjsonlog=/dev/null

# If parameter 1 is log then enable logging
if [[ "$1" == "log" ]]; then
  blockdegapperlog=/var/log/dmn/blockdegapper.log
  blocksjsonlog=/var/log/dmn/blocksjson.log
fi

# Sequentially run scripts
/usr/bin/nice -n 14 /opt/dmnctl/dmnblockdegapper test >> $blockdegapperlog
/usr/bin/nice -n 14 /opt/dmnctl/dmnblockparser >> $blockparserlog
/usr/bin/nice -n 14 /usr/bin/php /home/dash-www/www/api/cron.php test blocks24h >> $blocksjsonlog
/usr/bin/nice -n 14 /usr/bin/php /home/dash-www/www/api/cron.php test blockssuperblocks >> $blocksjsonlog
